### ISSUE TITLE
Controller Support

### ISSUE THREAD

**Issue by Vl4dimyr** [Vl4dimyr/CaptainShotgunModes#1]
Please let me know if you want controller support!

I will have to find out how to do this. And since there are fewer buttons on a controller I would rather cycle through the modes instead of selecting them, so that only one button is needed! But for this I need to find a button that is not used by anything else.

**Comment by ThatFoolishOne** [comment]
Controller support would be cool!

Maybe you could cycle through the modes with one of the dpad buttons? I don't think they're used for anything during gameplay.

**Comment by dlzaxo** [comment]
Controller support would be amazing.

I think custom controlls would be the best bet. Some people out there like to use pretty funky controls.

**Comment by InNoHurryToCode** [comment]
Controller support would indeed be very nice to have.
I agree with @ThatFoolishOne to first use one of the DPAD buttons, later on include @dlzaxo suggestion.

**Comment by Vl4dimyr** [comment]
Thanks for the feedback 👍☺️ I hope I can find time and my controller this week so I can work on this.

**Comment by Vl4dimyr** [comment]
[Support for non Xbox controllers](https://github.com/Vl4dimyr/CaptainShotgunModes/issues/5)
