### ISSUE TITLE
Dlc1/SotV compatibility, broken skill icons

### ISSUE THREAD

**Issue by Tsukino-uwu** [Vl4dimyr/CaptainShotgunModes#11]
#9 #10 these issues seems to be happening now again with the dlc/update

**Comment by Vl4dimyr** [comment]
I will investigate as soon as I can. I don't have the DLC yet, but I will see what I can do!

**Comment by Tsukino-uwu** [comment]
[LogOutput.log](https://github.com/Vl4dimyr/CaptainShotgunModes/files/8201805/LogOutput.log)
Only used BepInEx, HookGenPatcher, R2API & captainshotgun for this with a fresh profile on r2modman just to be extra sure no other mods would cause issues~
had no configs setup, started a singleplayer game as captain ( didn't try with other chars this time, but pretty sure it happens for all of them) , and then went back to the menu & exited the game
Hopefully something useful in the log, tried to make sure it would be short/informative 

no idea whats causing it, but these get spammed a lot
`[Error  : Unity Log] TypeLoadException: Could not resolve type with token 01000024 (from typeref, class/assembly UnityEngine.Input, UnityEngine.CoreModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null)
Stack trace:
CaptainShotgunModes.CaptainShotgunModesPlugin.Update () (at <d4adc827e2c6406988960ef0e16d7c2c>:IL_0001)`

`[Error  : Unity Log] MissingMethodException: void TMPro.TMP_Text.SetText(string)
Stack trace:
DMD<>?-1503227904.Hook<RoR2.UI.SkillIcon::Update>?1193135232 (RoR2.UI.SkillIcon ) (at <cc761b609a7840998fbf5612ce62254a>:IL_0014)`

**Comment by Bogdanov89** [comment]
this is such a phenomenal mod, cant wait for the SOTV update.
thank you!

**Comment by Vl4dimyr** [comment]
Sorry this took so long!
