### ISSUE TITLE
Does not work on controller

### ISSUE THREAD

**Issue by Kaizuto** [Vl4dimyr/CaptainShotgunModes#15]
For some reason it did not work on controller like the previous version (also applies bandit version)

**Comment by Vl4dimyr** [comment]
Hey, I did just test the mod with my Xbox 360 controller, and it works for me! Could you provide more information about your issue?

**Comment by Kaizuto** [comment]
It's probably because I installed a lot of mods, but clicking the Dpad doesn't change the modes for me, I had to use scroll wheel

**Comment by Vl4dimyr** [comment]
Please give the list of mods you are using, then I can maybe try to reproduce the issue ...

**Comment by Kaizuto** [comment]
feFG779VDg here is a profile code instead because there is a total of 100+ mods...

EDIT: Apparently it now works again (along with bandit), idk what happened but thanks tho, you can close this thread now
