### ISSUE TITLE
Configurable keys + ROO integration

### ISSUE THREAD

**Issue by Higgs1** [Vl4dimyr/CaptainShotgunModes#16]
Heyas, me again~

A friend of mine requested that the explicit mode selection keys (1, 2, 3) be configurable, and also for [Risk of Options](https://thunderstore.io/package/Rune580/Risk_Of_Options) integration, so that settings be configurable at any time in the game (even mid-run!) and also so they don't have to edit a text file some where. It was also suggested to add configurable keybinds for cycling the firing mode (in addition to the toggle-able scroll wheel).

I dunno if you or anyone else would be interested in those features, but they exist in my modpack now I suppose xD Feel free to ignore this whole issue if you're not interested! Below is a screenie of ROO's option pane. 

![Screenshot](https://user-images.githubusercontent.com/567651/163487357-6cf99ff3-4fce-499a-acde-e51e55c69c4d.png)

The drawback of adding ROO integration is of course an added dependency, which isn't an issue in my modpack because it already includes ROO. It could instead be made an optional dependency at the cost of extra coding.

Also I think it's pretty obvious that at least the two of us appreciate your mod and you for making it, thank you! :D

**Comment by Vl4dimyr** [comment]
Hey, thanks for letting me know about RoO, this sounds like a good idea! Although, I would definitely want to add it as a soft dependency, so it doesn't break the mod if it would be outdated/deprecated.

Making the mode selection keys and fire mode cycling configurable with RoO would be good, but if RoO is a soft dependency, I will also have to think about how to make things configurable via config file.

I don't know when I will find time for this, but I appreciate your and your friends' contribution!

**Comment by Vl4dimyr** [comment]
Hey, I've found some time =)

In 1.2.0 (https://github.com/Vl4dimyr/CaptainShotgunModes/pull/19) I did add RoO and made the selection keys configurable!

I'll think about the keybindings for the firing mode cycling and a toggle for the scroll wheel.
Thanks again for the suggestions!
