### ISSUE TITLE
Risk of Options menu icon

### ISSUE THREAD

**Issue by Higgs1** [Vl4dimyr/CaptainShotgunModes#20]
Hiyas :3

So this _has_ to be the most inconsequential thing, but...

![Screenshot from 2022-04-18 19-01-08](https://user-images.githubusercontent.com/567651/163898050-a25b75d4-9482-4e68-af65-1694070075dc.png)

I think adding an icon to ROO would be kinda neato. Take a look at 379a78a8d26d859b7c9bf2c5adffb6a1e056624d for how I implemented it. Sorry that code base deviates so much from yours, otherwise I'd have an actual PR ready to go (might still make one if I get around to it before you do). 

It does seem a bit redundant to have the mod's title text in the icon there as well though... maybe I'll see how it looks without the text later.

**Comment by Vl4dimyr** [comment]
Hey, thanks, I actually wanted to add the icon =)
I just had to make a small change. (See [RiskOfOptionsMod.cs:42](https://github.com/Vl4dimyr/CaptainShotgunModes/blob/master/RiskOfOptionsMod.cs#L42))
